### ISSUE TITLE
Error with python!

### ISSUE THREAD

**Issue by HENTAI-CODER** [mrmoein/GUI-DNS-changer-for-linux#4]
```
[[lain@LinuxLSD GUI-DNS-changer-for-linux]$ dns_changer
Traceback (most recent call last):
  File "/home/lain/GUI-DNS-changer-for-linux/main.py", line 2, in <module>
    from utils.initGui import GUI
  File "/home/lain/GUI-DNS-changer-for-linux/utils/initGui.py", line 4, in <module>
    from PyQt5 import QtWidgets, QtGui
ModuleNotFoundError: No module named 'PyQt5'
[lain@LinuxLSD GUI-DNS-changer-for-linux]$ ]
```

**Comment by HENTAI-CODER** [comment]
```
[lain@LinuxLSD GUI-DNS-changer-for-linux]$ pip install PyQt5
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by HENTAI-CODER** [comment]
`sudo pacman -S pyqt5`

fix it!✅
